### ISSUE TITLE
Create API

### ISSUE THREAD

**Issue by jhogoforbroke** [jhogoforbroke/steelseriesImagesyncTextSignboardMaker#1]
Implement an API interface to download rendered gifs

#### tasks to perform

- [ ] express configurations
- [ ] routes and controllers
- [ ] consume service functions from core
- [ ] download file process

#### pull request
TODO
